### ISSUE TITLE
Project Page Stable Baselines

### ISSUE THREAD

**Issue by araffin** [jaberkow/WaveRL#7]
Hello,

Nice project =)

Quick question: did you try other algorithms that are usually more suited for continuous actions? (like soft actor-critic (SAC), DDPG and TD3 (coming in the next release) which should be more sample efficient too)

We would also be interested if you could do a pull request on [stable-baselines](https://github.com/hill-a/stable-baselines) where you add your project to the [documentation](https://stable-baselines.readthedocs.io/en/master/misc/projects.html) (project section) ;)

**Comment by jaberkow** [comment]
Hi,

I just saw this (I keep forgetting that github doesn't auto subscribe you to threads on your own projects).  Thank you for checking it out, stable-baselines is an amazing package and really vital in getting this project off the ground.  I did try DDPG and it performed roughly as well as PPO2.  I haven't tried SAC however, so I can look into that this week actually.

What kind of information would you like in a pull request?  I can just post a blurb and links to the github repo and presentation.

**Comment by araffin** [comment]
>I haven't tried SAC however, so I can look into that this week actually.

Cool, don't forget to take a look at the rl zoo to have the proper hyperparameters ;) (same for TD3 which is an extension of DDPG and works as good as SAC)

> out, stable-baselines is an amazing package and really vital in getting this project off the ground. 

Thanks =)
